export interface Review {
  id: string; // Unique id generated by Firebase
  uid: string; // User id who created the Brewery
  breweryId: string; // The brewery this review belongs to
  title: string;
  text: string;
  createdOn: Date;
  rating: number;
}
