export interface User {
  id: string; // When creating a user, use the UID generated by Firebase
  displayName: string;
  email: string;
  profileImagePath: string; // Path from the storage bucket/folder that you will be reading from
  locked: boolean;
  dirthdate: Date;
  createdOn: Date;
}
